GET http://localhost:8080/api/tables
Authorization: Basic YWRtaW46YWRtaW5wYXNz
###
POST http://localhost:8080/api/tables
Authorization: Basic YWRtaW46YWRtaW5wYXNz
Content-Type: application/json

{
  "seats": 14,
  "available": true
}

###
GET http://localhost:8080/api/tables/2
Authorization: Basic YWRtaW46YWRtaW5wYXNz


###
DELETE http://localhost:8080/api/tables/2
Authorization: Basic YWRtaW46YWRtaW5wYXNz
