###
# Obtener todas las órdenes
GET http://localhost:8080/api/orders

###
# Obtener una orden por ID
GET http://localhost:8080/api/orders/search?text=2025-07-19

###
# Crear una nueva orden
POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "tableId": 2,
  "details": [
    {
      "dishId": 8,
      "quantity": 2
    },
    {
      "dishId": 5,
      "quantity": 2
    }
  ]
}



###
DELETE http://localhost:8080/api/orders/4

